## pip install notebook


## To run the notebook, Open the command prompt and type
jupyter notebook

In [1]:
print ( " Hai all this is how to display a text")

 Hai all this is how to display a text

In [2]:
#To Add two numbers

num1 = 20
num2 = 20
print (num1 + num2)

40

In [4]:
#Finding Square root of a number with the function sqrt() of math Library 

import math
num = 625 
root = math.sqrt(num) 
print("Square root= ", root)

Square root=  25.0

In [3]:
# Sample Program-2
# Write a program to calculate the area of a rectangle given the length and breadth are 50
# and 20 respectively.

length = 50
breadth = 20
area = length * breadth
print("Area of rectangle =", area)

Area of rectangle = 1000

In [ ]:
    # Sample Program-3
    # Write a program to read name and marks of a student and display the total marks

name = input("Enter Student's Name")
m1=float(input("Enter the Mark of English"))     # we are typcasting the input as float
m2=float(input("Enter the Mark of Artificial Intelligence") ) 
m3=float(input("Enter the Mark of Maths"))
                
Total= m1 + m2 + m3

print("Name : ", name)
print("Total Marks : ", Total)

Name :  4535
Total Marks :  396134.0

# Sample Program-4
## Asmita with her family went to a restaurant. Determine the choice of food according to the options she chooses from the main menu.

In [ ]:
# Case 1: All Members are vegetarians. They prefer to have veg food. No other options.
# (menu-veg)

choice = input("Enter the choice of food")
if choice == "veg":
    print("Welcome to Vegetarian Food House")

In [9]:
# Case 2: Family Members may choose non-vegetarian foods also if veg foods are not
# available. (menu-veg/Nonveg)

choice=input("Enter the choice of food") 
if choice == "veg":
    print("Welcome to Vegetarian Food House") 
else:
    print("Welcome to Non-vegetarian Foods")

Welcome to Non-vegetarian Foods

In [11]:
# Case 3: Family members can choose from variety of options like veg, non-veg, Mixed

print("Menu: Veg | Nonveg | Mixed") 
choice=input("Enter the choice of food")
if choice == "veg": 
    print("Welcome to Vegetarian Food House") 
elif choice == "nonveg":
    print("Welcome to Non-vegetarian Foods") 
else: 
    print("Welcome to your Favourite Choice of Foods")

Menu: Veg | Nonveg | Mixed
Welcome to Non-vegetarian Foods

# Sample Program-5
## Write a program to get the length of the sides of a triangle and determine whether it is equilateral triangle or isosceles triangle or scalene triangle.

In [ ]:
# Sample program to classify a triangle based on its sides
# Get user input for the Lengths of the sides

sidel = float(input("Enter the length of side 1: ")) 
side2 = float(input("Enter the length of side 2: ")) 
side3 = float(input("Enter the length of side 3: "))


# Check the type of triangle based on the Lengths of its sides 
if sidel == side2 == side3:
    print("It is an equilateral triangle.") 
elif sidel == side2 or sidel == side3 or side2 == side3: 
    print("It is an isosceles triangle.") 
else:
    print("It is a scalene triangle.")

![For Loop Diagram](pictures_for_notebook/for_loop.png)

In [ ]:
for i in range(1, 6):
    print("Iteration number:", i)

Iteration number: 1
Iteration number: 2
Iteration number: 3
Iteration number: 4
Iteration number: 5

In [9]:
# Sample Program-6
# Write a program to display even numbers and their squares between 100 and 110.

for num in range(100,110,2):
    square=num*num
    print(num, "squared is", square)

100 squared is 10000
102 squared is 10404
104 squared is 10816
106 squared is 11236
108 squared is 11664

In [10]:
# Sample Program-7
# Write a program to read a list, display each element and its type. (use type( ) to display the
# data type.)

my_list = [10, 15.5, "Hello", True, 25+5j , [1, 2, 3], (4, 5), {'a': 1, 'b': 2}]

for element in my_list:
    print("Element:", element, "Type:", type(element))

Element: 10 Type: <class 'int'>
Element: 15.5 Type: <class 'float'>
Element: Hello Type: <class 'str'>
Element: True Type: <class 'bool'>
Element: (25+5j) Type: <class 'complex'>
Element: [1, 2, 3] Type: <class 'list'>
Element: (4, 5) Type: <class 'tuple'>
Element: {'a': 1, 'b': 2} Type: <class 'dict'>

In [ ]:
# Sample Program-8
# Write a program to read a string. Split the string into list of words and display each word.

Str1="I am studying in Jyothis Central School" 
wordlist=Str1.split()
print ("Words in list format", wordlist) 
for word in wordlist:
    print (word)

Words in list format ['Iam', 'studying', 'in', 'Jyothis', 'Central', 'School']
Iam
studying
in
Jyothis
Central
School

In [1]:
# Sample Program-9
# Write a simple program to display the values stored in dictionary

my_dict = {'Name': 'Alice', 'Age': 25, 'City': 'New York'}  
for key, value in my_dict.items(): 
    print(f"{key}: {value}")

Name: Alice
Age: 25
City: New York

In [4]:
# Sample Program-10
# Write a Program to open a csv file students.csv and display its details

import csv
with open('students.csv', mode ='r')as file:
   
  # reading the CSV file
  csvFile = csv.reader(file)

  # displaying the contents of the CSV file
  for row in csvFile:
        print((row))

['RollNo', 'Name', 'class', 'TrName']
['11', 'Akshith', 'II', 'Sruthy']
['\'12"', " 'Ashmitha'", " 'VII'", " 'Ruby'"]
['\'13"', ' "MJ Anakha\'', " 'X'", " 'Jayasankar'"]
["'14'", " 'Nandana S'", " 'IX'", " 'Anu'"]
["'15'", " 'Neha S'", " 'V'", " 'Anu'"]
["'16'", " 'Neha T P'", " 'XII'", " 'Jayasankar'"]
["'17'", " 'Nishad P S'", " 'VIII'", " 'Ruby'"]
["'18'", " 'Pranav K S'", " 'VI'", " 'Sruthy'"]
["'19'", " 'Rithika R'", " 'IV'", " 'Anu'"]
["'20'", " 'Saanvi S'", " 'III'", " 'Sruthy'"]
[]
[]

# pip install numpy

# Creating a Numpy Array

In [6]:
# Using List of Tuples

import numpy as np
ar = np.array( [(99, 88, 77), (44, 55, 66)])
print ("Numpy Array:\n", ar)

Numpy Array:
 [[99 88 77]
 [44 55 66]]

In [1]:
# # Using values from the user (using empty( ) -- 
# The empty() function in numpy module of python is used to return a 
# new array of a 
# given size)

import numpy as np 
n=int(input("Enter the size of an array")) 
ar=np.empty(n) 
for i in range(n):
    ar[i]=int(input("Enter a number")) 
    
print("Array\n", ar)

Array
 [ 8. 89. 65. 65. 34.]

# The name "Pandas" has a reference to both "Panel Data", and "Python Data Analysis”.

## Pandas is built on top of the NumPy library which means that a lot of structures of NumPy are used or replicated in Pandas and Pandas is particularly wellsuited for working with tabular data, such as spreadsheets or SQL tables

## Creation of DataFrame

In [ ]:
# Using NumPy ndarrays

import numpy as np
import pandas as pd
    
array1 = np.array([10,20,30])
array2 = np.array([100, 200, 300])
array3 = np.array([-10, -20,-30])

pd.DataFrame( [array1, array2, array3] , 
             columns = ['col1', 'col2', 'col3']
            )

   col1  col2  col3
0    10    20    30
1   100   200   300
2   -10   -20   -30

In [ ]:
# Using List of Dictionaries

listDict = [{'Dance':10, 'Music':20}, 
            {'Dance':15, 'Music':10, 'Painting':20}, 
            {'Painting': 12}
            ]
df = pd.DataFrame(listDict, index=['X', 'XI', 'XII'])
print(df)


# Dictionary keys become column labels by default in a DataFrame, and
#  the lists become the rows.
# NaN (Not a Number) is inserted if a corresponding value for a column is missing.
# Pandas uses isnull() function to identify NaN values in a DataFrame.

     Dance  Music  Painting
X     10.0   20.0       NaN
XI    15.0   10.0      20.0
XII    NaN    NaN      12.0

# Dealing with Rows and Columns

In [3]:
# loading dataframe from a CSV file

import pandas as pd
Results = pd.read_csv('results.csv',)
Results.index = ['Maths', 'Science', 'Hindi']
print(Results)

         Rajat  Amrita  Meenakshi  Rose  Karthika
Maths       90      92         89    81        94
Science     91      81         91    71        95
Hindi       97      96         88    67        99

In [3]:
!pwd

/Users/subhankarmittra/Documents/git class 10 11 12/schoolTeachings/school_teachings/AI/11

# Adding a New Column to a DataFrame:

In [4]:
## We can add a new column ‘Fathima’, by mentioning column
#  name as given below

Results['Fathima' ]=[89,78,100]
print(Results)

         Rajat  Amrita  Meenakshi  Rose  Karthika  Fathima
Maths       90      92         89    81        94       89
Science     91      81         91    71        95       78
Hindi       97      96         88    67        99      100

In [6]:
# Adding a New Row to a DataFrame:
# We can add a new row to a DataFrame using the DataFrame.loc[ ] method

Results.loc['English'] = [90, 92, 89, 80, 90,90]
print(Results)

         Rajat  Amrita  Meenakshi  Rose  Karthika  Fathima
Maths       90      92         89    81        94       89
Science     91      81         91    71        95       78
Hindi       97      96         88    67        99      100
English     90      92         89    80        90       90

## Deleting Rows and Columns from a DataFrame

### We need to specify the names of the labels to be dropped and the axis from which they need to be dropped. 
delete a row, axis = 0 and 

deleting a column, axis = 1

In [7]:
Results = Results.drop('Hindi', axis=0)
print(Results)

         Rajat  Amrita  Meenakshi  Rose  Karthika  Fathima
Maths       90      92         89    81        94       89
Science     91      81         91    71        95       78
English     90      92         89    80        90       90

In [8]:
# Delete the columns having labels ‘Rajat’, 'Meenakshi' and ‘Karthika’’

Results = Results.drop(['Rajat', 'Meenakshi', 'Karthika'], axis=1)
print(Results)

         Amrita  Rose  Fathima
Maths        92    81       89
Science      81    71       78
English      92    80       90

# Accessing DataFrame Elements

 ### Two common ways of accessing are using loc and iloc. 
 #### DataFrame.loc[ ] uses label names for accessing 
#### DataFrame.iloc[ ] uses the index position for accessing the elements of a DataFrame

In [9]:
Results.loc['Science']

Amrita     81
Rose       71
Fathima    78
Name: Science, dtype: int64

In [10]:
Results.iloc[2]

Amrita     92
Rose       80
Fathima    90
Name: English, dtype: int64

# Understanding Missing Values

In [11]:
import pandas as pd
StudCCA = pd.read_csv('dance.csv')
StudCCA.index = ['X', 'XII', 'XII']
StudCCA

     Dance Music  Painting
X     10.0    20       NaN
XII   15.0    10      20.0
XII    NaN            12.0

In [ ]:
# Pandas provide a function isnull() to check whether any value is missing or not in the
# DataFrame. This function checks all attributes and returns True in case that attribute has
# missing values, otherwise returns False.


StudCCA.isnull()

     Dance  Music  Painting
X    False  False      True
XII  False  False     False
XII   True  False     False

In [13]:
# Finding any missing value in a column ➔ 

StudCCA['Music'].isnull().any()

False

In [ ]:
# Finding total number of NaN count per column

StudCCA.isnull().sum()

Dance       1
Music       0
Painting    1
dtype: int64

In [17]:
# Finding total number of NaN 

StudCCA.isnull().sum().sum()

2

In [19]:
# Deleting entire row with NaN values ➔ 

StudCCA.dropna()

     Dance Music  Painting
XII   15.0    10      20.0

In [ ]:
# but no change in actual dataframe -> not inplace 

StudCCA

     Dance Music  Painting
X     10.0    20       NaN
XII   15.0    10      20.0
XII    NaN            12.0

In [ ]:
# Replacing NaN values (here by 1) ➔ we generally use this to and later on 
# we see that it is useful in ML also

StudCCA.fillna(1)

     Dance Music  Painting
X     10.0    20       1.0
XII   15.0    10      20.0
XII    1.0            12.0

# Attributes of DataFrames
## Attributes are the properties of a DataFrame that can be used to fetch data or any information related to a particular DataFrame.

![DataFrame_Attribute](pictures_for_notebook/DataFrame_Attribute.png)

In [26]:
import pandas as pd

Teacher = pd.read_csv('Teacher.csv')
Teacher.index = ['Physics', 'Maths', 'Artificial Intelligence']

Teacher

                                 IX          X         XI             XII
Physics                  Jayasankar  Shanthini     Sruthy       Anand Raj
Maths                        Snitha  Haripriya  Praseetha  Sobhana Beegum
Artificial Intelligence     Noufiya     Rejila    Lekshmi           Jyoti

In [27]:
# Displaying Row Indexes - Teacher.index

Teacher.index

Index(['Physics', 'Maths', 'Artificial Intelligence'], dtype='object')

In [28]:
# Displaying column Indexes - Teacher.columns

Teacher.columns

Index(['IX', 'X', 'XI', 'XII'], dtype='object')

In [29]:
# Displaying datatype of each - Teacher.dtypes

Teacher.dtypes

IX     object
X      object
XI     object
XII    object
dtype: object

In [30]:
# Displaying data in Numpy Array form - Teacher.values

Teacher.values

array([['Jayasankar', 'Shanthini', 'Sruthy', 'Anand Raj'],
       ['Snitha', 'Haripriya', 'Praseetha', 'Sobhana Beegum'],
       ['Noufiya', 'Rejila', 'Lekshmi', 'Jyoti']], dtype=object)

In [31]:
# Displaying total number of rows and columns (row, column) - Teacher.shape
Teacher.shape

(3, 4)

In [32]:
# Displaying first n rows (here n = 2) - Teacher. head (2)

Teacher.head(2)

                 IX          X         XI             XII
Physics  Jayasankar  Shanthini     Sruthy       Anand Raj
Maths        Snitha  Haripriya  Praseetha  Sobhana Beegum

In [33]:
# Displaying last n rows (here n = 2) - Teacher. tail (2)

Teacher.tail(2)

                              IX          X         XI             XII
Maths                     Snitha  Haripriya  Praseetha  Sobhana Beegum
Artificial Intelligence  Noufiya     Rejila    Lekshmi           Jyoti

# Importing and Exporting Data between CSV Files and DataFrames

![read_csv_syntax](pictures_for_notebook/read_csv_syntax.png)

| Parameter   | Meaning                | Example                         |
| ----------- | ---------------------- | ------------------------------- |
| `filepath`  | Name/path of file      | `"data.csv"`                    |
| `sep`       | Separator used in file | `sep=","`                       |
| `header`    | Row with column names  | `header=0`                      |
| `names`     | Custom column names    | `names=["Roll","Name","Marks"]` |

![to_csv_syntax](pictures_for_notebook/to_csv_syntax.png)

# NEXT TOPIC MAY BE TAUGHT AFTER MACHINE LEARNING TOPIC

# Scikit-learn (Sklearn) 
### is the most useful and robust library for machine learning in Python. It provides a selection of efficient tools for machine learning and statistical modeling via a consistent interface in Python. Sklearn is built on (relies heavily on) NumPy, SciPy and Matplotlib

### Key Features:
- Offers a wide range of supervised and unsupervised learning algorithms.
- Provides tools for model selection, evaluation, and validation.
- Supports various tasks such as classification, regression, clustering, dimensionality reduction, and more.
- Integrates seamlessly with other Python libraries like NumPy, SciPy, and Pandas.

# load_iris (In sklearn.datasets)
- The Iris dataset is a classic and widely used dataset in machine learning, particularly for **classification tasks**. 
- It comprises measurements of various characteristics of iris flowers, such as 
    - sepal length, 
    - sepal width, 
    - petal length, and 
    - petal width, 

- The dataset typically includes three species: 
    - setosa, 
    - versicolor, and 
    - virginica.

In [2]:
pip install scikit-learn

Collecting scikit-learn
  Downloading scikit_learn-1.8.0-cp312-cp312-macosx_12_0_arm64.whl.metadata (11 kB)
Requirement already satisfied: numpy>=1.24.1 in /Users/subhankarmittra/anaconda3/envs/armlinux/lib/python3.12/site-packages (from scikit-learn) (2.0.1)
Collecting scipy>=1.10.0 (from scikit-learn)
  Downloading scipy-1.17.1-cp312-cp312-macosx_14_0_arm64.whl.metadata (62 kB)
Collecting joblib>=1.3.0 (from scikit-learn)
  Downloading joblib-1.5.3-py3-none-any.whl.metadata (5.5 kB)
Collecting threadpoolctl>=3.2.0 (from scikit-learn)
  Downloading threadpoolctl-3.6.0-py3-none-any.whl.metadata (13 kB)
Downloading scikit_learn-1.8.0-cp312-cp312-macosx_12_0_arm64.whl (8.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.1/8.1 MB 24.2 MB/s  0:00:00 eta 0:00:01
Downloading joblib-1.5.3-py3-none-any.whl (309 kB)
Downloading scipy-1.17.1-cp312-cp312-macosx_14_0_arm64.whl (20.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 20.3/20.3 MB 32.7 MB/s  0:00:00m0:00:0100:01
Downloading threadpoolctl-3.6.0-py3-none-any.whl (18 kB)
Installing collected packages: threadpoolctl, scipy, joblib, scikit-learn
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4/4 [scikit-learn][0m [scikit-learn]
Successfully installed joblib-1.5.3 scikit-learn-1.8.0 scipy-1.17.1 threadpoolctl-3.6.0
Note: you may need to restart the kernel to use updated packages.

![iris_species](pictures_for_notebook/iris_species.png)
# ----------------------------------------------
![target_and_feature_names](pictures_for_notebook/target_and_feature_names.png)

In [2]:
from sklearn.datasets import load_iris # importing iris dataset

iris = load_iris() # calls the “load_iris()” function to load the iris dataset

X = iris.data # X is a variable and assigned as feature vector. 
              #The feature vectors contain the input data for the machine learning model

y = iris.target # Y is a variable and assigned as target variable. 
                # The target variable contains the output or the variable we want to predict with the model.

In [3]:
(X)

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.2],
       [5. , 3.2, 1.2, 0.2],
       [5.5, 3.5, 1.3, 0.2],
       [4.9, 3.6, 1.4, 0.1],
       [4.4, 3. , 1.3, 0.2],
       [5.1, 3.4, 1.5, 0.2],
       [5. , 3.5, 1.3, 0.3],
       [4.5, 2.3, 1.3, 0.3],
       [4.4, 3.2, 1.3, 0.2],
       [5. , 3.5, 1.6, 0.6],
       [5.1, 3.8, 1.9, 0.4],
       [4.8, 3. , 1.4, 0.3],
       [5.1, 3.8, 1.6, 0.2],
       [4.6, 3.2, 1.4, 0.2],
       [5.3, 3.7, 1.5, 0.2],
       [5. , 3.3, 1.4, 0.2],
       [7. , 3.2, 4.7, 1.4],
       [6.4, 3.2, 4.5, 1.5],
       [6.9, 3.1, 4.9, 1.5],
       [5.5, 2.3, 4. , 1.3],
       [6.5, 2.8, 4.6, 1.5],
       [5.7, 2.8, 4.5, 1.3],
       [6.3, 3.3, 4.7, 1.6],
       [4.9, 2.4, 3.3, 1. ],
       [6.6, 2.9, 4.6, 1.3],
       [5.2, 2.7, 3.9, 1.4],
       [5. , 2. , 3.5, 1. ],
       [5.9, 3. , 4.2, 1.5],
       [6. , 2.2, 4. , 1. ],
       [6.1, 2.9, 4.7, 1.4],
       [5.6, 2.9, 3.6, 1.3],
       [6.7, 3.1, 4.4, 1.4],
       [5.6, 3. , 4.5, 1.5],
       [5.8, 2.7, 4.1, 1. ],
       [6.2, 2.2, 4.5, 1.5],
       [5.6, 2.5, 3.9, 1.1],
       [5.9, 3.2, 4.8, 1.8],
       [6.1, 2.8, 4. , 1.3],
       [6.3, 2.5, 4.9, 1.5],
       [6.1, 2.8, 4.7, 1.2],
       [6.4, 2.9, 4.3, 1.3],
       [6.6, 3. , 4.4, 1.4],
       [6.8, 2.8, 4.8, 1.4],
       [6.7, 3. , 5. , 1.7],
       [6. , 2.9, 4.5, 1.5],
       [5.7, 2.6, 3.5, 1. ],
       [5.5, 2.4, 3.8, 1.1],
       [5.5, 2.4, 3.7, 1. ],
       [5.8, 2.7, 3.9, 1.2],
       [6. , 2.7, 5.1, 1.6],
       [5.4, 3. , 4.5, 1.5],
       [6. , 3.4, 4.5, 1.6],
       [6.7, 3.1, 4.7, 1.5],
       [6.3, 2.3, 4.4, 1.3],
       [5.6, 3. , 4.1, 1.3],
       [5.5, 2.5, 4. , 1.3],
       [5.5, 2.6, 4.4, 1.2],
       [6.1, 3. , 4.6, 1.4],
       [5.8, 2.6, 4. , 1.2],
       [5. , 2.3, 3.3, 1. ],
       [5.6, 2.7, 4.2, 1.3],
       [5.7, 3. , 4.2, 1.2],
       [5.7, 2.9, 4.2, 1.3],
       [6.2, 2.9, 4.3, 1.3],
       [5.1, 2.5, 3. , 1.1],
       [5.7, 2.8, 4.1, 1.3],
       [6.3, 3.3, 6. , 2.5],
       [5.8, 2.7, 5.1, 1.9],
       [7.1, 3. , 5.9, 2.1],
       [6.3, 2.9, 5.6, 1.8],
       [6.5, 3. , 5.8, 2.2],
       [7.6, 3. , 6.6, 2.1],
       [4.9, 2.5, 4.5, 1.7],
       [7.3, 2.9, 6.3, 1.8],
       [6.7, 2.5, 5.8, 1.8],
       [7.2, 3.6, 6.1, 2.5],
       [6.5, 3.2, 5.1, 2. ],
       [6.4, 2.7, 5.3, 1.9],
       [6.8, 3. , 5.5, 2.1],
       [5.7, 2.5, 5. , 2. ],
       [5.8, 2.8, 5.1, 2.4],
       [6.4, 3.2, 5.3, 2.3],
       [6.5, 3. , 5.5, 1.8],
       [7.7, 3.8, 6.7, 2.2],
       [7.7, 2.6, 6.9, 2.3],
       [6. , 2.2, 5. , 1.5],
       [6.9, 3.2, 5.7, 2.3],
       [5.6, 2.8, 4.9, 2. ],
       [7.7, 2.8, 6.7, 2. ],
       [6.3, 2.7, 4.9, 1.8],
       [6.7, 3.3, 5.7, 2.1],
       [7.2, 3.2, 6. , 1.8],
       [6.2, 2.8, 4.8, 1.8],
       [6.1, 3. , 4.9, 1.8],
       [6.4, 2.8, 5.6, 2.1],
       [7.2, 3. , 5.8, 1.6],
       [7.4, 2.8, 6.1, 1.9],
       [7.9, 3.8, 6.4, 2. ],
       [6.4, 2.8, 5.6, 2.2],
       [6.3, 2.8, 5.1, 1.5],
       [6.1, 2.6, 5.6, 1.4],
       [7.7, 3. , 6.1, 2.3],
       [6.3, 3.4, 5.6, 2.4],
       [6.4, 3.1, 5.5, 1.8],
       [6. , 3. , 4.8, 1.8],
       [6.9, 3.1, 5.4, 2.1],
       [6.7, 3.1, 5.6, 2.4],
       [6.9, 3.1, 5.1, 2.3],
       [5.8, 2.7, 5.1, 1.9],
       [6.8, 3.2, 5.9, 2.3],
       [6.7, 3.3, 5.7, 2.5],
       [6.7, 3. , 5.2, 2.3],
       [6.3, 2.5, 5. , 1.9],
       [6.5, 3. , 5.2, 2. ],
       [6.2, 3.4, 5.4, 2.3],
       [5.9, 3. , 5.1, 1.8]])

| Feature Index | Feature Name      | What it Means (Simple) |
| ------------- | ----------------- | ---------------------- |
| X[:, 0]       | Sepal Length (cm) | Length of outer leaf   |
| X[:, 1]       | Sepal Width (cm)  | Width of outer leaf    |
| X[:, 2]       | Petal Length (cm) | Length of inner petal  |
| X[:, 3]       | Petal Width (cm)  | Width of inner petal   |

For example, the **first row [ 5.1, 3.5, 1.4, 0.2]** corresponds to an iris flower with the following measurements:
- Sepal length: 5.1 cm
- Sepal width: 3.5 cm
- Petal length: 1.4 cm
- Petal width: 0.2 cm

In [4]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

| Number | Flower Type |
| ------ | ----------- |
| 0      | Setosa      |
| 1      | Versicolor  |
| 2      | Virginica   |

# ---------------------------------------------------

# train_test_split (In sklearn.model_selection)
- Datasets are usually split into 
    - training set and 
    - testing set. 
    
- The training set is used to train the model and 
- testing set is used to test the model.

- Most common splitting ratio is 80: 20. 
    - (Training -> 80%, Testing-> 20%

In [5]:
# importing train_test_split
from sklearn.model_selection import train_test_split

# Splitting the dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=100)

X_train, y_train 

the feature vectors and target variables of the training set respectively.

X_test, y_test

the feature vectors and target variables of the testing set respectively.

test_size = 0.2

specifies that 20% of the data will be used for testing, and the remaining 80% will be used for training.

random_state = 1

Ensures reproducibility by fixing the random
seed. This means that every time you run the
code, the same split will be generated.


# ------------------------------------------

# KNeighborsClassifier (In sklearn.neighbors)

- Scikit-learn has wide range of Machine Learning (ML) algorithms which have a consistent interface for fitting, predicting accuracy, recall etc. 
- Here we are going to use KNN (K nearest neighbors) classifier.

In [6]:
from sklearn.neighbors import KNeighborsClassifier # importing KneighboursClassifier 
            #(type of supervised learning algorithm used for classification tasks.)

In [7]:
knn = KNeighborsClassifier(n_neighbors =3)

# we create an instance of the KNeighborsClassifier class . 
# n_neighbors = 3 indicates that the classifier will consider the 3 nearest neighbors 
# when making predictions. 
# This is a hyperparameter that can be tuned to improve the performance of the classifier.

In [8]:
knn.fit(X_train, y_train)

# trains the KNeighborsClassifier model using the fit method. 
# it constructs a representation of the training data that allows it to make
#  predictions based on the input features.

KNeighborsClassifier(n_neighbors=3)

In [9]:
y_pred = knn.predict(X_test)

# The knn object contains the trained model, 
# make predictions on new, unseen data.
y_pred

array([2, 0, 2, 0, 2, 2, 0, 0, 2, 0, 0, 2, 0, 0, 2, 1, 1, 1, 2, 2, 2, 0,
       2, 0, 1, 2, 1, 0, 1, 2])

In [10]:
y_test

array([2, 0, 2, 0, 2, 2, 0, 0, 2, 0, 0, 2, 0, 0, 2, 1, 1, 1, 2, 2, 2, 0,
       2, 0, 1, 2, 1, 0, 1, 2])

# metrics -> accuracy of the model

In [11]:
from sklearn import metrics
Accuracy = metrics.accuracy_score(y_test, y_pred)

# This calculates the accuracy of the model by comparing the predicted target values 
# (y_pred) 
# with the actual target values (y_test). The accuracy_score represents the proportion of
# correctly predicted instances out of all instances in the testing set.
Accuracy

1.0

### validate the model's predictive accuracy, we can use some sample data.

In [12]:
sample = [[5, 5, 3, 2], [2, 4, 3, 5]]
preds = knn.predict(sample)
pred_species=[]
for p in preds:
    pred_species.append(iris.target_names[p])

print("Predictions:",pred_species)

Predictions: [np.str_('setosa'), np.str_('virginica')]

# Complete Code

program that combines different parts of our project to make it complete and
understandable

In [ ]:
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn import metrics

# Load the iris dataset
iris = load_iris()
X = iris.data
y = iris.target 
# Split the dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=1) 
# Create an instance of the KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=3)
# Train the model
knn.fit(X_train, y_train)
# Make predictions on the test set
y_pred = knn.predict(X_test)
# Calculate accuracy
accuracy = metrics.accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)    

# Make predictions on new samples
sample = [[5, 5, 3, 2], [2, 4, 3, 5]] # fictious samples with 4 features each
preds = knn.predict(sample)
pred_species = []
for p in preds:
    pred_species.append(iris.target_names[p])
print("Predictions:", pred_species)

Accuracy: 1.0
Predictions: [np.str_('versicolor'), np.str_('virginica')]